### ISSUE TITLE
[Suggestions] Go mod support

### ISSUE THREAD

**Issue by maxkrivich** [bbl/go-ansible#1]
It would be nice if you can add go mod support, as far as I see right now there no dependencies YET, but in the future, if you want to distribute this package it might help.

```bash
$ go mod init github.com/bbl/go-ansible
```

**Comment by bbl** [comment]
Hey @maxkrivich!
Thanks for the tip, it definitely makes sense. I've just added go mod support in 8ba248a.
Closing the issue. Please feel free to reopen if needed.
